// Generated by scripts/emit_rust.py from schema/ + data/.
// Do not edit by hand: `python scripts/emit_rust.py --check` regenerates this
// file and fails on any difference, so a hand edit works until it silently does
// not.
//
// Zero dependencies. Everything is const data; nothing is parsed at runtime.
//
// The types below encode ClawBot's refusals so that a consumer cannot skip them
// by not having read an ADR. See ADR-0017.

#![forbid(unsafe_code)]
#![doc = "The ClawBot body model: links, joints, actuators, and what they can reach."]

use core::fmt;

/// An angle in **radians** — the unit every angular value in this repo is stored
/// in (ADR-0005), and the unit REP-103 puts URDF in.
///
/// Distinct from [`Degrees`] on purpose. Oh-Ben-Claw's `MovementCommand::ServoAngle`
/// takes degrees; this type exists so that crossing that boundary is a conversion
/// the compiler makes you write, at exactly one place, rather than a comment
/// somebody has to notice. The failure it prevents is a mechanism commanded to
/// 57 times the intended angle.
///
/// The guarantee, as an actually-executed test — this does not compile:
///
/// ```compile_fail
/// use clawbot::{Radians, Degrees};
/// fn commands_a_joint(_angle: Radians) {}
/// commands_a_joint(Degrees(90.0));
/// ```
///
/// and this does:
///
/// ```
/// use clawbot::{Radians, Degrees};
/// fn commands_a_joint(_angle: Radians) {}
/// commands_a_joint(Degrees(90.0).into());
/// ```
#[derive(Copy, Clone, PartialEq, PartialOrd, Debug)]
#[repr(transparent)]
pub struct Radians(pub f64);

/// An angle in **degrees**. Exists only so that a boundary conversion is explicit;
/// nothing in this repo stores degrees (ADR-0005).
#[derive(Copy, Clone, PartialEq, PartialOrd, Debug)]
#[repr(transparent)]
pub struct Degrees(pub f64);

impl From<Radians> for Degrees {
    fn from(r: Radians) -> Self {
        Degrees(r.0 * 180.0 / core::f64::consts::PI)
    }
}

impl From<Degrees> for Radians {
    fn from(d: Degrees) -> Self {
        Radians(d.0 * core::f64::consts::PI / 180.0)
    }
}

/// A length in **millimetres** (ADR-0005, inherited from OpenPartsCore and
/// OpenDesignCore ADR-0004). URDF is metres; [`Millimetres::to_metres`] is the
/// single conversion, and it is named rather than implicit.
#[derive(Copy, Clone, PartialEq, PartialOrd, Debug)]
#[repr(transparent)]
pub struct Millimetres(pub f64);

impl Millimetres {
    pub fn to_metres(self) -> f64 {
        self.0 / 1000.0
    }
}

/// Torque an actuator produces at the instant it stops moving, drawing a current
/// it cannot sustain.
///
/// **There is deliberately no conversion from this type to [`ContinuousTorque`].**
/// Not a `From` impl, not a `to_continuous()`, not a feature flag. ADR-0004's
/// central rule is that stall torque may never feed a capacity derivation, and
/// the 30–50%-of-stall rule of thumb spans a factor of 1.67 — choosing a point in
/// it is a guess. A consumer that wants to try must write that arithmetic in
/// their own code, where a reviewer can see it.
///
/// The guarantee, as an actually-executed test — neither of these compiles:
///
/// ```compile_fail
/// use clawbot::{StallTorque, ContinuousTorque};
/// let stall = StallTorque { newton_metres: 4.1, at_volts: 12.0, at_amps: None };
/// let _sized_on_this: ContinuousTorque = stall.into();
/// ```
///
/// ```compile_fail
/// use clawbot::StallTorque;
/// let stall = StallTorque { newton_metres: 4.1, at_volts: 12.0, at_amps: None };
/// let _ = stall.to_continuous();
/// ```
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct StallTorque {
    pub newton_metres: f64,
    /// Required. The same servo differs by 26% across its own rated range, so a
    /// torque figure without its voltage is not a figure (ADR-0014).
    pub at_volts: f64,
    pub at_amps: Option<f64>,
}

/// Torque a current-controlled actuator holds against, at a stated current per
/// phase.
///
/// Indexed by **current, not voltage** (ADR-0023). A stepper datasheet's "rated
/// voltage" is rated current times phase resistance — for the 17HS19-2004S1,
/// 2.0 A x 1.4 ohm = 2.8 V exactly — so it carries no information the other two
/// figures do not, and it is not the supply the motor runs on. This type has no
/// `at_volts` field for that reason.
///
/// **No conversion to [`ContinuousTorque`]**, for the same reason
/// [`StallTorque`] has none: whether a holding torque is sustainable is not
/// something the datasheet says, so turning one into a capacity figure would be
/// a guess with a type signature.
///
/// ```compile_fail
/// use clawbot::{HoldingTorque, ContinuousTorque};
/// let holding = HoldingTorque { newton_metres: 0.59, at_amps: 2.0 };
/// let _sized_on_this: ContinuousTorque = holding.into();
/// ```
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct HoldingTorque {
    pub newton_metres: f64,
    /// Required, per phase. The index a row is looked up by.
    pub at_amps: f64,
}

/// Torque an actuator can sustain. **The only torque that may size a mechanism**
/// (ADR-0004).
///
/// Most datasheets do not publish one — including good ones. When the slice is
/// empty, capacity is not derivable and the honest answer is "incomplete", not a
/// fraction of stall.
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct ContinuousTorque {
    pub newton_metres: f64,
    pub at_volts: f64,
    /// How the figure was established. A rule of thumb applied to stall torque is
    /// not a determination.
    pub how_determined: &'static str,
}

/// What a joint may be commanded to do. **Absent means UNKNOWN, never unlimited**
/// — which is why every field that can be unknown is an `Option` and why the
/// whole struct appears as `Option<JointLimits>` on a [`Joint`].
///
/// Rust makes the caller confront the `None`. That is inherited invariant #3
/// moved out of a document and into something the compiler will not let you skip.
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct JointLimits {
    pub lower: Option<Radians>,
    pub upper: Option<Radians>,
    pub lower_mm: Option<Millimetres>,
    pub upper_mm: Option<Millimetres>,
    /// Maximum torque the joint may be commanded to produce. Distinct from the
    /// actuator's continuous torque; a capacity derivation takes the lesser.
    pub effort_nm: Option<f64>,
    pub velocity_rad_s: Option<f64>,
}

/// URDF's six joint types (ADR-0009).
#[derive(Copy, Clone, PartialEq, Eq, Debug)]
pub enum JointType {
    Revolute,
    Continuous,
    Prismatic,
    Fixed,
    /// Six degrees of freedom. Its pose is not determined by the mechanism, so a
    /// derivation across it answers incomplete: a world pose comes from a
    /// localization stack, which this repo does not model (ADR-0009).
    Floating,
    /// Motion in a plane. Says the base moves; does not say how.
    Planar,
}

impl JointType {
    pub const fn as_str(self) -> &'static str {
        match self {
            JointType::Revolute => "revolute",
            JointType::Continuous => "continuous",
            JointType::Prismatic => "prismatic",
            JointType::Fixed => "fixed",
            JointType::Floating => "floating",
            JointType::Planar => "planar",
        }
    }

    /// Whether this joint's travel is bounded by the mechanism at all. `false`
    /// for floating and planar, whose travel is bounded by an environment this
    /// repo does not model.
    pub const fn is_bounded_by_mechanism(self) -> bool {
        matches!(self, JointType::Revolute | JointType::Prismatic)
    }
}

impl fmt::Display for JointType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

/// One joint's value as a fixed function of another's: `multiplier * other +
/// offset` (ADR-0008).
///
/// A mimicking joint is **not independently commandable**. A caller sampling the
/// configuration space must not treat it as a free axis.
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct Mimic {
    pub joint: &'static str,
    pub multiplier: f64,
    pub offset: f64,
}

#[derive(Copy, Clone, PartialEq, Debug)]
pub struct Vec3 {
    pub x: f64,
    pub y: f64,
    pub z: f64,
}

/// A pose relative to the parent frame. Rotation is fixed-axis roll-pitch-yaw
/// applied in X, Y, Z order, right-handed — REP-103's convention and URDF's.
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct Transform {
    pub xyz_mm: Vec3,
    pub rpy_rad: Vec3,
}

/// A rigid body. Exactly one of the three kinds is populated (ADR-0006); the
/// referenced part or artifact is **stored, not resolved** — a consumer needing a
/// mass reads OpenPartsCore itself.
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct Link {
    pub id: &'static str,
    pub part_id: Option<&'static str>,
    pub provenance_sha256: Option<&'static str>,
    /// Bounding box of a fabricated link, in millimetres. Declared design intent,
    /// not a measurement.
    pub make_size_mm: Option<Vec3>,
    pub make_material: Option<&'static str>,
    /// Only where the mass is not obtainable from `part_id` or the provenance
    /// record. `None` means a static capacity derivation reports incomplete
    /// rather than assuming zero.
    pub mass_g: Option<f64>,
}

#[derive(Copy, Clone, PartialEq, Debug)]
pub struct Joint {
    pub id: &'static str,
    pub kind: JointType,
    pub parent: &'static str,
    pub child: &'static str,
    pub origin: Transform,
    /// `None` where the format or the author did not state one. Never defaulted
    /// to (1,0,0) here, whatever `urdfdom` does (ADR-0007).
    pub axis: Option<Vec3>,
    /// `None` means UNKNOWN, never unlimited.
    pub limits: Option<JointLimits>,
    pub mimic: Option<Mimic>,
    pub actuator_id: Option<&'static str>,
    pub gear_ratio: Option<f64>,
}

/// A mechanism: a tree of links joined by joints. Note what is absent — there is
/// no reach field (ADR-0003) and no payload field (ADR-0004), because both are
/// derived, per-pose, and carry the assumptions that make them true.
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct Robot {
    pub id: &'static str,
    pub kind: &'static str,
    pub make: Option<&'static str>,
    pub model: Option<&'static str>,
    /// Every transform and every derived answer is relative to this frame, and
    /// none of them is a world claim (ADR-0009).
    pub base_link: &'static str,
    pub links: &'static [Link],
    pub joints: &'static [Joint],
}

impl Robot {
    /// Joints whose travel nobody has sourced. While this is non-empty, a
    /// reachability computation answers "incomplete" naming these, and URDF
    /// export refuses (ADR-0003, ADR-0007).
    pub fn joints_without_limits(&self) -> impl Iterator<Item = &'static Joint> + '_ {
        self.joints
            .iter()
            .filter(|j| j.kind.is_bounded_by_mechanism() && j.limits.is_none())
    }

    /// Joints a caller may set. A mimicking joint follows another and is not one.
    pub fn free_joints(&self) -> impl Iterator<Item = &'static Joint> + '_ {
        self.joints
            .iter()
            .filter(|j| j.kind != JointType::Fixed && j.mimic.is_none())
    }

    pub fn joint(&self, id: &str) -> Option<&'static Joint> {
        self.joints.iter().find(|j| j.id == id)
    }

    pub fn link(&self, id: &str) -> Option<&'static Link> {
        self.links.iter().find(|l| l.id == id)
    }
}

/// A quantity that varies **unit to unit** rather than over an operating
/// envelope, so it is stored as a range and never collapsed to a value
/// (ADR-0021).
///
/// **The two ends answer opposite questions, and picking one silently is wrong
/// in a direction that depends on what the caller is asking:**
///
/// - *"Can this hold a load unpowered?"* — use `min`. Your unit might be the
///   loose one, and assuming otherwise means a load that slips.
/// - *"Will this back-drive when I need it to?"* — for hand-guiding, or a fault
///   that must not lock a joint — use `max`. Your unit might be the stiff one.
///
/// There is deliberately no `typical`: it would be read as the answer, the range
/// would become decoration, and no vendor publishes one — a midpoint invented
/// here would be a number with no source sitting between two that have one.
///
/// Nothing in this crate derives from these. The tempting inference — that a
/// load below the backdriving minimum is held with no actuator torque — is a
/// physical claim this repo has no source for, and its failure mode is a joint
/// that lets go.
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct TorqueRange {
    pub min: f64,
    pub max: f64,
    /// The vendor's method, and the original units where a conversion happened.
    pub how_determined: &'static str,
    pub basis: Option<Basis>,
}

/// Whether a value describes the **product line** or the **unit on your bench**
/// (ADR-0018).
///
/// Not pedantry. Harmonic Drive states in a datasheet that its published torsional
/// stiffness is "the average of many tests of actual units" and that "the spring
/// rate of an individual unit may vary within approximately ±30% of the average".
/// A cited value has meant "somebody published it" everywhere else in this
/// platform; this is a vendor saying their number describes a population.
///
/// Carried as `Option<Basis>`, and `None` means **unknown** — never "assumed
/// exact". A derivation must report the weakest basis it consumed.
#[derive(Copy, Clone, PartialEq, Eq, Debug)]
pub enum Basis {
    /// Describes a product line. An individual unit may sit outside it.
    ModelTypical,
    /// Measured on the specific hardware.
    ThisUnit,
}

impl Basis {
    pub const fn as_str(self) -> &'static str {
        match self {
            Basis::ModelTypical => "model-typical",
            Basis::ThisUnit => "this-unit",
        }
    }
}

#[derive(Copy, Clone, PartialEq, Debug)]
pub struct Actuator {
    pub id: &'static str,
    pub make: Option<&'static str>,
    pub model: Option<&'static str>,
    pub kind: &'static str,
    pub part_id: Option<&'static str>,
    /// Recorded because datasheets publish it, and omitting the field invites
    /// someone to write it into the continuous slice. Not usable for sizing.
    pub stall_torque: &'static [StallTorque],
    /// Frequently empty, including on good datasheets. Empty means capacity is
    /// not derivable (ADR-0004).
    pub continuous_torque: &'static [ContinuousTorque],
    /// Current-indexed headline for steppers and BLDCs (ADR-0023). Empty for a
    /// servo, and empty is not zero.
    pub holding_torque: &'static [HoldingTorque],
    pub gear_ratio: Option<f64>,
    /// `None` means UNKNOWN, never zero. Backlash is why a commanded pose and an
    /// achieved pose differ.
    pub backlash_rad: Option<Radians>,
    pub mass_g: Option<f64>,
    /// Input torque required to begin motion. A range, never a value.
    pub starting_torque_nm: Option<TorqueRange>,
    /// Output torque required to turn the input — what a stationary geartrain
    /// resists. A range, and **its two ends answer opposite questions**; see
    /// [`TorqueRange`].
    pub backdriving_torque_nm: Option<TorqueRange>,
    /// Whether this actuator's figures describe the product line or your unit.
    /// `None` is unknown, and a derivation consuming it must say so (ADR-0018).
    pub basis: Option<Basis>,
    /// Unit-to-unit variation the vendor states, as a percentage. `None` means the
    /// spread is unknown, not zero.
    pub spread_pct: Option<f64>,
}

// NOTE: there is no `efficiency` field, and its absence is a decision rather than
// an omission (ADR-0018). Efficiency varies with input speed, ratio, load,
// temperature and lubricant — Harmonic Drive publishes eight curves and no scalar
// — and, more to the point, efficiency curves describe a gearbox that is TURNING.
// A static hold has an input speed of zero, where no efficiency curve exists.
// What governs a stationary geartrain is starting and backdriving torque, which
// this crate does not carry because nothing has yet needed them.

impl Actuator {
    /// The continuous rating at exactly this supply voltage, if one was published.
    ///
    /// **There is no interpolating variant** (ADR-0014). Torque against voltage is
    /// approximately linear for a DC motor and "approximately" is a model — an
    /// unsourced one, whose output would be indistinguishable on the page from a
    /// datasheet value.
    pub fn continuous_at(&self, volts: f64) -> Option<&'static ContinuousTorque> {
        self.continuous_torque
            .iter()
            .find(|t| (t.at_volts - volts).abs() < 1e-9)
    }

    /// Whether a capacity derivation is possible at all. `false` for most
    /// actuators, which is a true statement about the available evidence rather
    /// than a gap to be filled.
    pub fn capacity_derivable(&self) -> bool {
        !self.continuous_torque.is_empty()
    }
}

/// How a command physically reaches an actuator. Determines what a controller can
/// **know** as much as what it can do: a `Pwm` actuator reports nothing back.
#[derive(Copy, Clone, PartialEq, Eq, Debug)]
pub enum Bus {
    Pwm,
    I2c,
    Spi,
    Uart,
    Can,
    Rs485,
    StepDir,
}

/// Whatever the controller calls this output — a PWM channel number, a bus id, a
/// CAN node id. Carried verbatim in whichever form the controller uses.
#[derive(Copy, Clone, PartialEq, Eq, Debug)]
pub enum ChannelId {
    Number(i64),
    Name(&'static str),
}

/// One driven joint's entry in the control contract (ADR-0010).
///
/// This is the type ADR-0017 was written for. The `Radians`/`Degrees` split only
/// pays for itself at a boundary, and **this is the boundary**: Oh-Ben-Claw's
/// `MovementCommand::ServoAngle` takes degrees, every value here is radians, and
/// [`Channel::actuator_angle`] is the one place the two meet.
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct Channel {
    pub joint_id: &'static str,
    pub channel: Option<ChannelId>,
    pub bus: Option<Bus>,
    pub bus_address: Option<ChannelId>,
    /// True when a positive command produces motion in the negative direction of
    /// the joint's declared axis. A fact about how the thing was physically
    /// installed, and **the most common reason a correct model drives a mechanism
    /// into its own end stop**.
    pub inverted: bool,
    /// The actuator's zero expressed in joint coordinates. Corke names this as a
    /// distinct ambiguity a DH table cannot carry: a mechanism's zero-angle pose
    /// and its controller's zero-angle pose are routinely different.
    pub zero_offset: Option<Radians>,
}

impl Channel {
    /// Convert a joint value into the angle this actuator should be commanded to,
    /// applying inversion and zero offset.
    ///
    /// Returns [`Radians`], deliberately. A consumer whose wire format is degrees
    /// converts at its own boundary and the conversion is visible in one line:
    ///
    /// ```
    /// use clawbot::{Channel, Radians, Degrees};
    /// let ch = Channel {
    ///     joint_id: "elbow", channel: None, bus: None, bus_address: None,
    ///     inverted: true, zero_offset: Some(Radians(0.1)),
    /// };
    /// let command: Degrees = ch.actuator_angle(Radians(0.5)).into();
    /// assert!((command.0 - (-0.4_f64).to_degrees()).abs() < 1e-12);
    /// ```
    ///
    /// It lives here rather than in each consumer so that every consumer applies
    /// the same arithmetic. Publishing the contract is not commanding: nothing in
    /// this crate reaches hardware (ADR-0010).
    pub fn actuator_angle(&self, joint: Radians) -> Radians {
        let sign = if self.inverted { -1.0 } else { 1.0 };
        Radians(sign * joint.0 + self.zero_offset.map_or(0.0, |o| o.0))
    }
}

/// A cable, and the joints it crosses. **A cable that crosses a joint is a joint
/// limit** (ADR-0012): unless somebody left slack, it binds before the joint does.
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct CableRun {
    pub id: &'static str,
    pub crosses: &'static [&'static str],
    /// **`None` means NOBODY CHECKED** — never that it is fine. `Option<bool>` is
    /// load-bearing here: the compiler will not let a caller collapse the unknown
    /// case into the false case without writing it down.
    pub permits_full_travel: Option<bool>,
    /// Where the harness binds tighter than the joint. Only ever a limit somebody
    /// established, with a method.
    pub travel_limit: &'static [HarnessTravelLimit],
}

#[derive(Copy, Clone, PartialEq, Debug)]
pub struct HarnessTravelLimit {
    pub joint_id: &'static str,
    pub lower: Option<Radians>,
    pub upper: Option<Radians>,
    pub how_determined: &'static str,
}

#[derive(Copy, Clone, PartialEq, Debug)]
pub struct Power {
    /// Load-bearing: a torque figure is meaningless without its voltage, and a
    /// capacity derivation selects the actuator row matching THIS value
    /// (ADR-0014). `None` means no derivation is possible.
    pub supply_volts: Option<f64>,
    pub supply_current_a: Option<f64>,
    /// If true, an actuator stall can brown out the controller — turning a
    /// mechanical problem into a loss of control.
    pub shared_with_logic: Option<bool>,
}

/// What connects the actuators to the thing that drives them, and to power.
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct Harness {
    pub id: &'static str,
    pub robot_id: &'static str,
    pub controller_part_id: Option<&'static str>,
    pub channels: &'static [Channel],
    pub routing: &'static [CableRun],
    pub power: Power,
}

impl Harness {
    pub fn channel_for(&self, joint_id: &str) -> Option<&'static Channel> {
        self.channels.iter().find(|c| c.joint_id == joint_id)
    }

    /// Cable runs that cross a joint where nobody established what travel they
    /// permit. While this is non-empty, any reachability answer over this
    /// mechanism **over-claims**, and must say so (ADR-0012).
    pub fn unchecked_runs(&self) -> impl Iterator<Item = &'static CableRun> + '_ {
        self.routing.iter().filter(|r| {
            !r.crosses.is_empty()
                && r.permits_full_travel.is_none()
                && r.travel_limit.is_empty()
        })
    }
}

// NOTE: assemblies are not emitted. An assembly is a DAG of steps for a person at
// a bench — fasteners, torques, what cannot be undone — and no runtime consumes
// it. Adding it here would be data nothing reads, which ADR-0017's whole argument
// is against. It stays in `data/assemblies/` as JSON.

pub fn robot(id: &str) -> Option<&'static Robot> {
    ROBOTS.iter().find(|r| r.id == id)
}

pub fn actuator(id: &str) -> Option<&'static Actuator> {
    ACTUATORS.iter().find(|a| a.id == id)
}

/// The harness wiring a given robot, if one has been recorded. `None` means the
/// cable routing is unknown, which is not the same as "there are no cables".
pub fn harness_for(robot_id: &str) -> Option<&'static Harness> {
    HARNESSES.iter().find(|h| h.robot_id == robot_id)
}

/// Every robot record, sorted by id.
pub const ROBOTS: &[Robot] = &[
    Robot {
        id: "pan-tilt-mg90s",
        kind: "pan-tilt",
        make: None,
        model: None,
        base_link: "base",
        links: &[
        Link {
            id: "base",
            part_id: None,
            provenance_sha256: None,
            make_size_mm: Some(Vec3 { x: 1.0_f64, y: 1.0_f64, z: 1.0_f64 }),
            make_material: Some("petg"),
            mass_g: None,
        },
        Link {
            id: "yoke",
            part_id: None,
            provenance_sha256: None,
            make_size_mm: Some(Vec3 { x: 1.0_f64, y: 1.0_f64, z: 1.0_f64 }),
            make_material: Some("petg"),
            mass_g: None,
        },
        Link {
            id: "head",
            part_id: None,
            provenance_sha256: None,
            make_size_mm: Some(Vec3 { x: 1.0_f64, y: 1.0_f64, z: 1.0_f64 }),
            make_material: Some("petg"),
            mass_g: None,
        },
        ],
        joints: &[
        Joint {
            id: "pan",
            kind: JointType::Revolute,
            parent: "base",
            child: "yoke",
            origin: Transform { xyz_mm: Vec3 { x: 0.0_f64, y: 0.0_f64, z: 1.0_f64 }, rpy_rad: Vec3 { x: 0.0_f64, y: 0.0_f64, z: 0.0_f64 } },
            axis: Some(Vec3 { x: 0.0_f64, y: 0.0_f64, z: 1.0_f64 }),
            limits: None,
            mimic: None,
            actuator_id: Some("towerpro-mg90s"),
            gear_ratio: Some(1.0_f64),
        },
        Joint {
            id: "tilt",
            kind: JointType::Revolute,
            parent: "yoke",
            child: "head",
            origin: Transform { xyz_mm: Vec3 { x: 0.0_f64, y: 0.0_f64, z: 1.0_f64 }, rpy_rad: Vec3 { x: 0.0_f64, y: 0.0_f64, z: 0.0_f64 } },
            axis: Some(Vec3 { x: 0.0_f64, y: 1.0_f64, z: 0.0_f64 }),
            limits: None,
            mimic: None,
            actuator_id: Some("towerpro-mg90s"),
            gear_ratio: Some(1.0_f64),
        },
        ],
    },
];

/// Every actuator record, sorted by id.
pub const ACTUATORS: &[Actuator] = &[
    Actuator {
        id: "dynamixel-xm430-w350",
        make: Some("ROBOTIS"),
        model: Some("XM430-W350-T/R"),
        kind: "smart-servo",
        part_id: Some("electronic/dynamixel-xm430-w350"),
        stall_torque: &[
            StallTorque { newton_metres: 3.8_f64, at_volts: 11.1_f64, at_amps: Some(2.1_f64) },
            StallTorque { newton_metres: 4.1_f64, at_volts: 12.0_f64, at_amps: Some(2.3_f64) },
            StallTorque { newton_metres: 4.8_f64, at_volts: 14.8_f64, at_amps: Some(2.7_f64) },
        ],
        holding_torque: &[
        ],
        continuous_torque: &[
        ],
        gear_ratio: Some(353.5_f64),
        backlash_rad: None,
        mass_g: Some(82.0_f64),
        starting_torque_nm: None,
        backdriving_torque_nm: None,
        basis: None,
        spread_pct: None,
    },
    Actuator {
        id: "towerpro-mg90s",
        make: Some("TowerPro"),
        model: Some("MG90S"),
        kind: "hobby-servo",
        part_id: None,
        stall_torque: &[
            StallTorque { newton_metres: 0.1765197_f64, at_volts: 4.8_f64, at_amps: None },
            StallTorque { newton_metres: 0.2157463_f64, at_volts: 6.0_f64, at_amps: None },
        ],
        holding_torque: &[
        ],
        continuous_torque: &[
        ],
        gear_ratio: None,
        backlash_rad: None,
        mass_g: Some(13.4_f64),
        starting_torque_nm: None,
        backdriving_torque_nm: None,
        basis: None,
        spread_pct: None,
    },
];

/// Every harness record, sorted by id. This is the control contract
/// ADR-0010 promised: joint to physical output, plus the two facts no
/// amount of modelling recovers — which way it was installed, and where
/// its zero is.
pub const HARNESSES: &[Harness] = &[
];
