// Generated by scripts/emit_rust.py from schema/ + data/.
// Do not edit by hand: `python scripts/emit_rust.py --check` regenerates this
// file and fails on any difference, so a hand edit works until it silently does
// not.
//
// Zero dependencies. Everything is const data; nothing is parsed at runtime.
//
// The types below encode ClawBot's refusals so that a consumer cannot skip them
// by not having read an ADR. See ADR-0017.

#![forbid(unsafe_code)]
#![doc = "The ClawBot body model: links, joints, actuators, and what they can reach."]

use core::fmt;

/// An angle in **radians** — the unit every angular value in this repo is stored
/// in (ADR-0005), and the unit REP-103 puts URDF in.
///
/// Distinct from [`Degrees`] on purpose. Oh-Ben-Claw's `MovementCommand::ServoAngle`
/// takes degrees; this type exists so that crossing that boundary is a conversion
/// the compiler makes you write, at exactly one place, rather than a comment
/// somebody has to notice. The failure it prevents is a mechanism commanded to
/// 57 times the intended angle.
///
/// The guarantee, as an actually-executed test — this does not compile:
///
/// ```compile_fail
/// use clawbot::{Radians, Degrees};
/// fn commands_a_joint(_angle: Radians) {}
/// commands_a_joint(Degrees(90.0));
/// ```
///
/// and this does:
///
/// ```
/// use clawbot::{Radians, Degrees};
/// fn commands_a_joint(_angle: Radians) {}
/// commands_a_joint(Degrees(90.0).into());
/// ```
#[derive(Copy, Clone, PartialEq, PartialOrd, Debug)]
#[repr(transparent)]
pub struct Radians(pub f64);

/// An angle in **degrees**. Exists only so that a boundary conversion is explicit;
/// nothing in this repo stores degrees (ADR-0005).
#[derive(Copy, Clone, PartialEq, PartialOrd, Debug)]
#[repr(transparent)]
pub struct Degrees(pub f64);

impl From<Radians> for Degrees {
    fn from(r: Radians) -> Self {
        Degrees(r.0 * 180.0 / core::f64::consts::PI)
    }
}

impl From<Degrees> for Radians {
    fn from(d: Degrees) -> Self {
        Radians(d.0 * core::f64::consts::PI / 180.0)
    }
}

/// A length in **millimetres** (ADR-0005, inherited from OpenPartsCore and
/// OpenDesignCore ADR-0004). URDF is metres; [`Millimetres::to_metres`] is the
/// single conversion, and it is named rather than implicit.
#[derive(Copy, Clone, PartialEq, PartialOrd, Debug)]
#[repr(transparent)]
pub struct Millimetres(pub f64);

impl Millimetres {
    pub fn to_metres(self) -> f64 {
        self.0 / 1000.0
    }
}

/// Torque an actuator produces at the instant it stops moving, drawing a current
/// it cannot sustain.
///
/// **There is deliberately no conversion from this type to [`ContinuousTorque`].**
/// Not a `From` impl, not a `to_continuous()`, not a feature flag. ADR-0004's
/// central rule is that stall torque may never feed a capacity derivation, and
/// the 30–50%-of-stall rule of thumb spans a factor of 1.67 — choosing a point in
/// it is a guess. A consumer that wants to try must write that arithmetic in
/// their own code, where a reviewer can see it.
///
/// The guarantee, as an actually-executed test — neither of these compiles:
///
/// ```compile_fail
/// use clawbot::{StallTorque, ContinuousTorque};
/// let stall = StallTorque { newton_metres: 4.1, at_volts: 12.0, at_amps: None };
/// let _sized_on_this: ContinuousTorque = stall.into();
/// ```
///
/// ```compile_fail
/// use clawbot::StallTorque;
/// let stall = StallTorque { newton_metres: 4.1, at_volts: 12.0, at_amps: None };
/// let _ = stall.to_continuous();
/// ```
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct StallTorque {
    pub newton_metres: f64,
    /// Required. The same servo differs by 26% across its own rated range, so a
    /// torque figure without its voltage is not a figure (ADR-0014).
    pub at_volts: f64,
    pub at_amps: Option<f64>,
}

/// Torque an actuator can sustain. **The only torque that may size a mechanism**
/// (ADR-0004).
///
/// Most datasheets do not publish one — including good ones. When the slice is
/// empty, capacity is not derivable and the honest answer is "incomplete", not a
/// fraction of stall.
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct ContinuousTorque {
    pub newton_metres: f64,
    pub at_volts: f64,
    /// How the figure was established. A rule of thumb applied to stall torque is
    /// not a determination.
    pub how_determined: &'static str,
}

/// What a joint may be commanded to do. **Absent means UNKNOWN, never unlimited**
/// — which is why every field that can be unknown is an `Option` and why the
/// whole struct appears as `Option<JointLimits>` on a [`Joint`].
///
/// Rust makes the caller confront the `None`. That is inherited invariant #3
/// moved out of a document and into something the compiler will not let you skip.
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct JointLimits {
    pub lower: Option<Radians>,
    pub upper: Option<Radians>,
    pub lower_mm: Option<Millimetres>,
    pub upper_mm: Option<Millimetres>,
    /// Maximum torque the joint may be commanded to produce. Distinct from the
    /// actuator's continuous torque; a capacity derivation takes the lesser.
    pub effort_nm: Option<f64>,
    pub velocity_rad_s: Option<f64>,
}

/// URDF's six joint types (ADR-0009).
#[derive(Copy, Clone, PartialEq, Eq, Debug)]
pub enum JointType {
    Revolute,
    Continuous,
    Prismatic,
    Fixed,
    /// Six degrees of freedom. Its pose is not determined by the mechanism, so a
    /// derivation across it answers incomplete: a world pose comes from a
    /// localization stack, which this repo does not model (ADR-0009).
    Floating,
    /// Motion in a plane. Says the base moves; does not say how.
    Planar,
}

impl JointType {
    pub const fn as_str(self) -> &'static str {
        match self {
            JointType::Revolute => "revolute",
            JointType::Continuous => "continuous",
            JointType::Prismatic => "prismatic",
            JointType::Fixed => "fixed",
            JointType::Floating => "floating",
            JointType::Planar => "planar",
        }
    }

    /// Whether this joint's travel is bounded by the mechanism at all. `false`
    /// for floating and planar, whose travel is bounded by an environment this
    /// repo does not model.
    pub const fn is_bounded_by_mechanism(self) -> bool {
        matches!(self, JointType::Revolute | JointType::Prismatic)
    }
}

impl fmt::Display for JointType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

/// One joint's value as a fixed function of another's: `multiplier * other +
/// offset` (ADR-0008).
///
/// A mimicking joint is **not independently commandable**. A caller sampling the
/// configuration space must not treat it as a free axis.
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct Mimic {
    pub joint: &'static str,
    pub multiplier: f64,
    pub offset: f64,
}

#[derive(Copy, Clone, PartialEq, Debug)]
pub struct Vec3 {
    pub x: f64,
    pub y: f64,
    pub z: f64,
}

/// A pose relative to the parent frame. Rotation is fixed-axis roll-pitch-yaw
/// applied in X, Y, Z order, right-handed — REP-103's convention and URDF's.
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct Transform {
    pub xyz_mm: Vec3,
    pub rpy_rad: Vec3,
}

/// A rigid body. Exactly one of the three kinds is populated (ADR-0006); the
/// referenced part or artifact is **stored, not resolved** — a consumer needing a
/// mass reads OpenPartsCore itself.
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct Link {
    pub id: &'static str,
    pub part_id: Option<&'static str>,
    pub provenance_sha256: Option<&'static str>,
    /// Bounding box of a fabricated link, in millimetres. Declared design intent,
    /// not a measurement.
    pub make_size_mm: Option<Vec3>,
    pub make_material: Option<&'static str>,
    /// Only where the mass is not obtainable from `part_id` or the provenance
    /// record. `None` means a static capacity derivation reports incomplete
    /// rather than assuming zero.
    pub mass_g: Option<f64>,
}

#[derive(Copy, Clone, PartialEq, Debug)]
pub struct Joint {
    pub id: &'static str,
    pub kind: JointType,
    pub parent: &'static str,
    pub child: &'static str,
    pub origin: Transform,
    /// `None` where the format or the author did not state one. Never defaulted
    /// to (1,0,0) here, whatever `urdfdom` does (ADR-0007).
    pub axis: Option<Vec3>,
    /// `None` means UNKNOWN, never unlimited.
    pub limits: Option<JointLimits>,
    pub mimic: Option<Mimic>,
    pub actuator_id: Option<&'static str>,
    pub gear_ratio: Option<f64>,
}

/// A mechanism: a tree of links joined by joints. Note what is absent — there is
/// no reach field (ADR-0003) and no payload field (ADR-0004), because both are
/// derived, per-pose, and carry the assumptions that make them true.
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct Robot {
    pub id: &'static str,
    pub kind: &'static str,
    pub make: Option<&'static str>,
    pub model: Option<&'static str>,
    /// Every transform and every derived answer is relative to this frame, and
    /// none of them is a world claim (ADR-0009).
    pub base_link: &'static str,
    pub links: &'static [Link],
    pub joints: &'static [Joint],
}

impl Robot {
    /// Joints whose travel nobody has sourced. While this is non-empty, a
    /// reachability computation answers "incomplete" naming these, and URDF
    /// export refuses (ADR-0003, ADR-0007).
    pub fn joints_without_limits(&self) -> impl Iterator<Item = &'static Joint> + '_ {
        self.joints
            .iter()
            .filter(|j| j.kind.is_bounded_by_mechanism() && j.limits.is_none())
    }

    /// Joints a caller may set. A mimicking joint follows another and is not one.
    pub fn free_joints(&self) -> impl Iterator<Item = &'static Joint> + '_ {
        self.joints
            .iter()
            .filter(|j| j.kind != JointType::Fixed && j.mimic.is_none())
    }

    pub fn joint(&self, id: &str) -> Option<&'static Joint> {
        self.joints.iter().find(|j| j.id == id)
    }

    pub fn link(&self, id: &str) -> Option<&'static Link> {
        self.links.iter().find(|l| l.id == id)
    }
}

#[derive(Copy, Clone, PartialEq, Debug)]
pub struct Actuator {
    pub id: &'static str,
    pub make: Option<&'static str>,
    pub model: Option<&'static str>,
    pub kind: &'static str,
    pub part_id: Option<&'static str>,
    /// Recorded because datasheets publish it, and omitting the field invites
    /// someone to write it into the continuous slice. Not usable for sizing.
    pub stall_torque: &'static [StallTorque],
    /// Frequently empty, including on good datasheets. Empty means capacity is
    /// not derivable (ADR-0004).
    pub continuous_torque: &'static [ContinuousTorque],
    pub gear_ratio: Option<f64>,
    /// `None` means UNKNOWN, never zero. Backlash is why a commanded pose and an
    /// achieved pose differ.
    pub backlash_rad: Option<Radians>,
    pub mass_g: Option<f64>,
}

impl Actuator {
    /// The continuous rating at exactly this supply voltage, if one was published.
    ///
    /// **There is no interpolating variant** (ADR-0014). Torque against voltage is
    /// approximately linear for a DC motor and "approximately" is a model — an
    /// unsourced one, whose output would be indistinguishable on the page from a
    /// datasheet value.
    pub fn continuous_at(&self, volts: f64) -> Option<&'static ContinuousTorque> {
        self.continuous_torque
            .iter()
            .find(|t| (t.at_volts - volts).abs() < 1e-9)
    }

    /// Whether a capacity derivation is possible at all. `false` for most
    /// actuators, which is a true statement about the available evidence rather
    /// than a gap to be filled.
    pub fn capacity_derivable(&self) -> bool {
        !self.continuous_torque.is_empty()
    }
}

pub fn robot(id: &str) -> Option<&'static Robot> {
    ROBOTS.iter().find(|r| r.id == id)
}

pub fn actuator(id: &str) -> Option<&'static Actuator> {
    ACTUATORS.iter().find(|a| a.id == id)
}

/// Every robot record, sorted by id.
pub const ROBOTS: &[Robot] = &[
];

/// Every actuator record, sorted by id.
pub const ACTUATORS: &[Actuator] = &[
    Actuator {
        id: "dynamixel-xm430-w350",
        make: Some("ROBOTIS"),
        model: Some("XM430-W350-T/R"),
        kind: "smart-servo",
        part_id: None,
        stall_torque: &[
            StallTorque { newton_metres: 3.8_f64, at_volts: 11.1_f64, at_amps: Some(2.1_f64) },
            StallTorque { newton_metres: 4.1_f64, at_volts: 12.0_f64, at_amps: Some(2.3_f64) },
            StallTorque { newton_metres: 4.8_f64, at_volts: 14.8_f64, at_amps: Some(2.7_f64) },
        ],
        continuous_torque: &[
        ],
        gear_ratio: Some(353.5_f64),
        backlash_rad: None,
        mass_g: Some(82.0_f64),
    },
];
