#!/usr/bin/env python3
"""Emit the Rust binding from schema + data (ADR-0017, adopting OPC ADR-0003).

    python scripts/emit_rust.py            # write bindings/rust/src/lib.rs
    python scripts/emit_rust.py --check    # exit 1 if the committed file is stale

Zero dependencies on purpose, matching OpenPartsCore: Oh-Ben-Claw is the intended
consumer and should not take serde to read a static body model.

**The types are the point, not the data.** Every refusal in this repo is
otherwise a convention enforced by a validator, a docstring and an ADR — all of
which are advice. Here they are compile errors:

* `Radians` and `Degrees` are distinct, and conversion is explicit. Oh-Ben-Claw's
  `ServoAngle` is degrees and this repo is radians (ADR-0010); the seam now fails
  to compile instead of failing on the bench.
* `StallTorque` and `ContinuousTorque` are distinct **with no conversion between
  them**, because ADR-0004 says stall may never feed a capacity derivation. A
  consumer that wants the fraction must write it themselves, where review sees it.
* Unknown is `Option`, never a sentinel zero — invariant #3, enforced by the
  compiler rather than by having read a document.

The type definitions live in this file as a literal header and the records are
generated below it. If a type needs changing, change it *here* — editing
`lib.rs` directly works right up until the next regeneration reverts it.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "bindings" / "rust" / "src" / "lib.rs"


def rs(value) -> str:
    """Rust literal for a string or None."""
    if value is None:
        return "None"
    return f"Some({json.dumps(value, ensure_ascii=False)})"


def rs_str(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def rs_f64(value) -> str:
    if value is None:
        return "None"
    return f"Some({float(value)!r}_f64)"


def load(directory: str, key: str) -> list[dict]:
    path = ROOT / "data" / directory
    if not path.exists():
        return []
    entries = [json.loads(p.read_text(encoding="utf-8"))
               for p in sorted(path.glob("*.json"))]
    entries.sort(key=lambda e: e.get(key, ""))
    return entries


HEADER = '''// Generated by scripts/emit_rust.py from schema/ + data/.
// Do not edit by hand: `python scripts/emit_rust.py --check` regenerates this
// file and fails on any difference, so a hand edit works until it silently does
// not.
//
// Zero dependencies. Everything is const data; nothing is parsed at runtime.
//
// The types below encode ClawBot's refusals so that a consumer cannot skip them
// by not having read an ADR. See ADR-0017.

#![forbid(unsafe_code)]
#![doc = "The ClawBot body model: links, joints, actuators, and what they can reach."]

use core::fmt;

/// An angle in **radians** — the unit every angular value in this repo is stored
/// in (ADR-0005), and the unit REP-103 puts URDF in.
///
/// Distinct from [`Degrees`] on purpose. Oh-Ben-Claw's `MovementCommand::ServoAngle`
/// takes degrees; this type exists so that crossing that boundary is a conversion
/// the compiler makes you write, at exactly one place, rather than a comment
/// somebody has to notice. The failure it prevents is a mechanism commanded to
/// 57 times the intended angle.
///
/// The guarantee, as an actually-executed test — this does not compile:
///
/// ```compile_fail
/// use clawbot::{Radians, Degrees};
/// fn commands_a_joint(_angle: Radians) {}
/// commands_a_joint(Degrees(90.0));
/// ```
///
/// and this does:
///
/// ```
/// use clawbot::{Radians, Degrees};
/// fn commands_a_joint(_angle: Radians) {}
/// commands_a_joint(Degrees(90.0).into());
/// ```
#[derive(Copy, Clone, PartialEq, PartialOrd, Debug)]
#[repr(transparent)]
pub struct Radians(pub f64);

/// An angle in **degrees**. Exists only so that a boundary conversion is explicit;
/// nothing in this repo stores degrees (ADR-0005).
#[derive(Copy, Clone, PartialEq, PartialOrd, Debug)]
#[repr(transparent)]
pub struct Degrees(pub f64);

impl From<Radians> for Degrees {
    fn from(r: Radians) -> Self {
        Degrees(r.0 * 180.0 / core::f64::consts::PI)
    }
}

impl From<Degrees> for Radians {
    fn from(d: Degrees) -> Self {
        Radians(d.0 * core::f64::consts::PI / 180.0)
    }
}

/// A length in **millimetres** (ADR-0005, inherited from OpenPartsCore and
/// OpenDesignCore ADR-0004). URDF is metres; [`Millimetres::to_metres`] is the
/// single conversion, and it is named rather than implicit.
#[derive(Copy, Clone, PartialEq, PartialOrd, Debug)]
#[repr(transparent)]
pub struct Millimetres(pub f64);

impl Millimetres {
    pub fn to_metres(self) -> f64 {
        self.0 / 1000.0
    }
}

/// Torque an actuator produces at the instant it stops moving, drawing a current
/// it cannot sustain.
///
/// **There is deliberately no conversion from this type to [`ContinuousTorque`].**
/// Not a `From` impl, not a `to_continuous()`, not a feature flag. ADR-0004's
/// central rule is that stall torque may never feed a capacity derivation, and
/// the 30–50%-of-stall rule of thumb spans a factor of 1.67 — choosing a point in
/// it is a guess. A consumer that wants to try must write that arithmetic in
/// their own code, where a reviewer can see it.
///
/// The guarantee, as an actually-executed test — neither of these compiles:
///
/// ```compile_fail
/// use clawbot::{StallTorque, ContinuousTorque};
/// let stall = StallTorque { newton_metres: 4.1, at_volts: 12.0, at_amps: None };
/// let _sized_on_this: ContinuousTorque = stall.into();
/// ```
///
/// ```compile_fail
/// use clawbot::StallTorque;
/// let stall = StallTorque { newton_metres: 4.1, at_volts: 12.0, at_amps: None };
/// let _ = stall.to_continuous();
/// ```
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct StallTorque {
    pub newton_metres: f64,
    /// Required. The same servo differs by 26% across its own rated range, so a
    /// torque figure without its voltage is not a figure (ADR-0014).
    pub at_volts: f64,
    pub at_amps: Option<f64>,
}

/// Torque a current-controlled actuator holds against, at a stated current per
/// phase.
///
/// Indexed by **current, not voltage** (ADR-0023). A stepper datasheet's "rated
/// voltage" is rated current times phase resistance — for the 17HS19-2004S1,
/// 2.0 A x 1.4 ohm = 2.8 V exactly — so it carries no information the other two
/// figures do not, and it is not the supply the motor runs on. This type has no
/// `at_volts` field for that reason.
///
/// **No conversion to [`ContinuousTorque`]**, for the same reason
/// [`StallTorque`] has none: whether a holding torque is sustainable is not
/// something the datasheet says, so turning one into a capacity figure would be
/// a guess with a type signature.
///
/// ```compile_fail
/// use clawbot::{HoldingTorque, ContinuousTorque};
/// let holding = HoldingTorque { newton_metres: 0.59, at_amps: 2.0 };
/// let _sized_on_this: ContinuousTorque = holding.into();
/// ```
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct HoldingTorque {
    pub newton_metres: f64,
    /// Required, per phase. The index a row is looked up by.
    pub at_amps: f64,
}

/// Force a linear actuator produces at the limit, in newtons.
///
/// **Newtons are not newton-metres** (ADR-0025). Force and torque are separate
/// types here so that a unit error is a compile error rather than a number that
/// looks ordinary. Actuonix calls this "Max Force (lifted)".
///
/// **No conversion to [`ContinuousForce`]**, matching [`StallTorque`]. The
/// Actuonix L12 publishes a 20% maximum duty cycle, which is a vendor saying
/// its headline force is not a continuous rating.
///
/// ```compile_fail
/// use clawbot::{StallForce, ContinuousForce};
/// let peak = StallForce { newtons: 80.0, at_volts: 12.0, at_amps: None };
/// let _sized_on_this: ContinuousForce = peak.into();
/// ```
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct StallForce {
    pub newtons: f64,
    /// Required. The L12 ships in 6 V and 12 V variants with different force
    /// figures, so a force without its voltage is not a figure.
    pub at_volts: f64,
    pub at_amps: Option<f64>,
}

/// Force a linear actuator can sustain. **The only force that may size a
/// mechanism** (ADR-0004, ADR-0025).
///
/// Expect this slice to be empty. Empty means capacity is not derivable, and is
/// never a licence to take a fraction of [`StallForce`].
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct ContinuousForce {
    pub newtons: f64,
    pub at_volts: f64,
    pub how_determined: &'static str,
}

/// Torque an actuator can sustain. **The only torque that may size a mechanism**
/// (ADR-0004).
///
/// Most datasheets do not publish one — including good ones. When the slice is
/// empty, capacity is not derivable and the honest answer is "incomplete", not a
/// fraction of stall.
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct ContinuousTorque {
    pub newton_metres: f64,
    pub at_volts: f64,
    /// How the figure was established. A rule of thumb applied to stall torque is
    /// not a determination.
    pub how_determined: &'static str,
}

/// What a joint may be commanded to do. **Absent means UNKNOWN, never unlimited**
/// — which is why every field that can be unknown is an `Option` and why the
/// whole struct appears as `Option<JointLimits>` on a [`Joint`].
///
/// Rust makes the caller confront the `None`. That is inherited invariant #3
/// moved out of a document and into something the compiler will not let you skip.
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct JointLimits {
    pub lower: Option<Radians>,
    pub upper: Option<Radians>,
    pub lower_mm: Option<Millimetres>,
    pub upper_mm: Option<Millimetres>,
    /// Maximum torque the joint may be commanded to produce. Distinct from the
    /// actuator's continuous torque; a capacity derivation takes the lesser.
    pub effort_nm: Option<f64>,
    pub velocity_rad_s: Option<f64>,
}

/// URDF's six joint types (ADR-0009).
#[derive(Copy, Clone, PartialEq, Eq, Debug)]
pub enum JointType {
    Revolute,
    Continuous,
    Prismatic,
    Fixed,
    /// Six degrees of freedom. Its pose is not determined by the mechanism, so a
    /// derivation across it answers incomplete: a world pose comes from a
    /// localization stack, which this repo does not model (ADR-0009).
    Floating,
    /// Motion in a plane. Says the base moves; does not say how.
    Planar,
}

impl JointType {
    pub const fn as_str(self) -> &'static str {
        match self {
            JointType::Revolute => "revolute",
            JointType::Continuous => "continuous",
            JointType::Prismatic => "prismatic",
            JointType::Fixed => "fixed",
            JointType::Floating => "floating",
            JointType::Planar => "planar",
        }
    }

    /// Whether this joint's travel is bounded by the mechanism at all. `false`
    /// for floating and planar, whose travel is bounded by an environment this
    /// repo does not model.
    pub const fn is_bounded_by_mechanism(self) -> bool {
        matches!(self, JointType::Revolute | JointType::Prismatic)
    }
}

impl fmt::Display for JointType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

/// One joint's value as a fixed function of another's: `multiplier * other +
/// offset` (ADR-0008).
///
/// A mimicking joint is **not independently commandable**. A caller sampling the
/// configuration space must not treat it as a free axis.
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct Mimic {
    pub joint: &'static str,
    pub multiplier: f64,
    pub offset: f64,
}

#[derive(Copy, Clone, PartialEq, Debug)]
pub struct Vec3 {
    pub x: f64,
    pub y: f64,
    pub z: f64,
}

/// A pose relative to the parent frame. Rotation is fixed-axis roll-pitch-yaw
/// applied in X, Y, Z order, right-handed — REP-103's convention and URDF's.
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct Transform {
    pub xyz_mm: Vec3,
    pub rpy_rad: Vec3,
}

/// A rigid body. Exactly one of the three kinds is populated (ADR-0006); the
/// referenced part or artifact is **stored, not resolved** — a consumer needing a
/// mass reads OpenPartsCore itself.
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct Link {
    pub id: &'static str,
    pub part_id: Option<&'static str>,
    pub provenance_sha256: Option<&'static str>,
    /// Bounding box of a fabricated link, in millimetres. Declared design intent,
    /// not a measurement.
    pub make_size_mm: Option<Vec3>,
    pub make_material: Option<&'static str>,
    /// Only where the mass is not obtainable from `part_id` or the provenance
    /// record. `None` means a static capacity derivation reports incomplete
    /// rather than assuming zero.
    pub mass_g: Option<f64>,
}

#[derive(Copy, Clone, PartialEq, Debug)]
pub struct Joint {
    pub id: &'static str,
    pub kind: JointType,
    pub parent: &'static str,
    pub child: &'static str,
    pub origin: Transform,
    /// `None` where the format or the author did not state one. Never defaulted
    /// to (1,0,0) here, whatever `urdfdom` does (ADR-0007).
    pub axis: Option<Vec3>,
    /// `None` means UNKNOWN, never unlimited.
    pub limits: Option<JointLimits>,
    pub mimic: Option<Mimic>,
    pub actuator_id: Option<&'static str>,
    pub gear_ratio: Option<f64>,
}

/// A mechanism: a tree of links joined by joints. Note what is absent — there is
/// no reach field (ADR-0003) and no payload field (ADR-0004), because both are
/// derived, per-pose, and carry the assumptions that make them true.
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct Robot {
    pub id: &'static str,
    pub kind: &'static str,
    pub make: Option<&'static str>,
    pub model: Option<&'static str>,
    /// Every transform and every derived answer is relative to this frame, and
    /// none of them is a world claim (ADR-0009).
    pub base_link: &'static str,
    pub links: &'static [Link],
    pub joints: &'static [Joint],
}

impl Robot {
    /// Joints whose travel nobody has sourced. While this is non-empty, a
    /// reachability computation answers "incomplete" naming these, and URDF
    /// export refuses (ADR-0003, ADR-0007).
    pub fn joints_without_limits(&self) -> impl Iterator<Item = &'static Joint> + '_ {
        self.joints
            .iter()
            .filter(|j| j.kind.is_bounded_by_mechanism() && j.limits.is_none())
    }

    /// Joints a caller may set. A mimicking joint follows another and is not one.
    pub fn free_joints(&self) -> impl Iterator<Item = &'static Joint> + '_ {
        self.joints
            .iter()
            .filter(|j| j.kind != JointType::Fixed && j.mimic.is_none())
    }

    pub fn joint(&self, id: &str) -> Option<&'static Joint> {
        self.joints.iter().find(|j| j.id == id)
    }

    pub fn link(&self, id: &str) -> Option<&'static Link> {
        self.links.iter().find(|l| l.id == id)
    }
}

/// A quantity that varies **unit to unit** rather than over an operating
/// envelope, so it is stored as a range and never collapsed to a value
/// (ADR-0021).
///
/// **The two ends answer opposite questions, and picking one silently is wrong
/// in a direction that depends on what the caller is asking:**
///
/// - *"Can this hold a load unpowered?"* — use `min`. Your unit might be the
///   loose one, and assuming otherwise means a load that slips.
/// - *"Will this back-drive when I need it to?"* — for hand-guiding, or a fault
///   that must not lock a joint — use `max`. Your unit might be the stiff one.
///
/// There is deliberately no `typical`: it would be read as the answer, the range
/// would become decoration, and no vendor publishes one — a midpoint invented
/// here would be a number with no source sitting between two that have one.
///
/// Nothing in this crate derives from these. The tempting inference — that a
/// load below the backdriving minimum is held with no actuator torque — is a
/// physical claim this repo has no source for, and its failure mode is a joint
/// that lets go.
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct TorqueRange {
    pub min: f64,
    pub max: f64,
    /// The vendor's method, and the original units where a conversion happened.
    pub how_determined: &'static str,
    pub basis: Option<Basis>,
}

/// Whether a value describes the **product line** or the **unit on your bench**
/// (ADR-0018).
///
/// Not pedantry. Harmonic Drive states in a datasheet that its published torsional
/// stiffness is "the average of many tests of actual units" and that "the spring
/// rate of an individual unit may vary within approximately ±30% of the average".
/// A cited value has meant "somebody published it" everywhere else in this
/// platform; this is a vendor saying their number describes a population.
///
/// Carried as `Option<Basis>`, and `None` means **unknown** — never "assumed
/// exact". A derivation must report the weakest basis it consumed.
#[derive(Copy, Clone, PartialEq, Eq, Debug)]
pub enum Basis {
    /// Describes a product line. An individual unit may sit outside it.
    ModelTypical,
    /// Measured on the specific hardware.
    ThisUnit,
}

impl Basis {
    pub const fn as_str(self) -> &'static str {
        match self {
            Basis::ModelTypical => "model-typical",
            Basis::ThisUnit => "this-unit",
        }
    }
}

#[derive(Copy, Clone, PartialEq, Debug)]
pub struct Actuator {
    pub id: &'static str,
    pub make: Option<&'static str>,
    pub model: Option<&'static str>,
    pub kind: &'static str,
    pub part_id: Option<&'static str>,
    /// Recorded because datasheets publish it, and omitting the field invites
    /// someone to write it into the continuous slice. Not usable for sizing.
    pub stall_torque: &'static [StallTorque],
    /// Frequently empty, including on good datasheets. Empty means capacity is
    /// not derivable (ADR-0004).
    pub continuous_torque: &'static [ContinuousTorque],
    /// Current-indexed headline for steppers and BLDCs (ADR-0023). Empty for a
    /// servo, and empty is not zero.
    pub holding_torque: &'static [HoldingTorque],
    /// Newtons, for linear actuators only (ADR-0025). Empty for everything that
    /// produces a torque.
    pub stall_force: &'static [StallForce],
    /// The only force that may size a mechanism. Empty on every datasheet read
    /// so far.
    pub continuous_force: &'static [ContinuousForce],
    /// The vendor's stated maximum duty cycle. `None` is UNKNOWN, never 100.
    pub duty_cycle_pct: Option<f64>,
    pub gear_ratio: Option<f64>,
    /// `None` means UNKNOWN, never zero. Backlash is why a commanded pose and an
    /// achieved pose differ.
    pub backlash_rad: Option<Radians>,
    pub mass_g: Option<f64>,
    /// Input torque required to begin motion. A range, never a value.
    pub starting_torque_nm: Option<TorqueRange>,
    /// Output torque required to turn the input — what a stationary geartrain
    /// resists. A range, and **its two ends answer opposite questions**; see
    /// [`TorqueRange`].
    pub backdriving_torque_nm: Option<TorqueRange>,
    /// Whether this actuator's figures describe the product line or your unit.
    /// `None` is unknown, and a derivation consuming it must say so (ADR-0018).
    pub basis: Option<Basis>,
    /// Unit-to-unit variation the vendor states, as a percentage. `None` means the
    /// spread is unknown, not zero.
    pub spread_pct: Option<f64>,
}

// NOTE: there is no `efficiency` field, and its absence is a decision rather than
// an omission (ADR-0018). Efficiency varies with input speed, ratio, load,
// temperature and lubricant — Harmonic Drive publishes eight curves and no scalar
// — and, more to the point, efficiency curves describe a gearbox that is TURNING.
// A static hold has an input speed of zero, where no efficiency curve exists.
// What governs a stationary geartrain is starting and backdriving torque, which
// this crate does not carry because nothing has yet needed them.

impl Actuator {
    /// The continuous rating at exactly this supply voltage, if one was published.
    ///
    /// **There is no interpolating variant** (ADR-0014). Torque against voltage is
    /// approximately linear for a DC motor and "approximately" is a model — an
    /// unsourced one, whose output would be indistinguishable on the page from a
    /// datasheet value.
    pub fn continuous_at(&self, volts: f64) -> Option<&'static ContinuousTorque> {
        self.continuous_torque
            .iter()
            .find(|t| (t.at_volts - volts).abs() < 1e-9)
    }

    /// Whether a capacity derivation is possible at all. `false` for most
    /// actuators, which is a true statement about the available evidence rather
    /// than a gap to be filled.
    pub fn capacity_derivable(&self) -> bool {
        !self.continuous_torque.is_empty()
    }
}

/// How a command physically reaches an actuator. Determines what a controller can
/// **know** as much as what it can do: a `Pwm` actuator reports nothing back.
#[derive(Copy, Clone, PartialEq, Eq, Debug)]
pub enum Bus {
    Pwm,
    I2c,
    Spi,
    Uart,
    Can,
    Rs485,
    StepDir,
}

/// Whatever the controller calls this output — a PWM channel number, a bus id, a
/// CAN node id. Carried verbatim in whichever form the controller uses.
#[derive(Copy, Clone, PartialEq, Eq, Debug)]
pub enum ChannelId {
    Number(i64),
    Name(&'static str),
}

/// One driven joint's entry in the control contract (ADR-0010).
///
/// This is the type ADR-0017 was written for. The `Radians`/`Degrees` split only
/// pays for itself at a boundary, and **this is the boundary**: Oh-Ben-Claw's
/// `MovementCommand::ServoAngle` takes degrees, every value here is radians, and
/// [`Channel::actuator_angle`] is the one place the two meet.
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct Channel {
    pub joint_id: &'static str,
    pub channel: Option<ChannelId>,
    pub bus: Option<Bus>,
    pub bus_address: Option<ChannelId>,
    /// True when a positive command produces motion in the negative direction of
    /// the joint's declared axis. A fact about how the thing was physically
    /// installed, and **the most common reason a correct model drives a mechanism
    /// into its own end stop**.
    pub inverted: bool,
    /// The actuator's zero expressed in joint coordinates. Corke names this as a
    /// distinct ambiguity a DH table cannot carry: a mechanism's zero-angle pose
    /// and its controller's zero-angle pose are routinely different.
    pub zero_offset: Option<Radians>,
}

impl Channel {
    /// Convert a joint value into the angle this actuator should be commanded to,
    /// applying inversion and zero offset.
    ///
    /// Returns [`Radians`], deliberately. A consumer whose wire format is degrees
    /// converts at its own boundary and the conversion is visible in one line:
    ///
    /// ```
    /// use clawbot::{Channel, Radians, Degrees};
    /// let ch = Channel {
    ///     joint_id: "elbow", channel: None, bus: None, bus_address: None,
    ///     inverted: true, zero_offset: Some(Radians(0.1)),
    /// };
    /// let command: Degrees = ch.actuator_angle(Radians(0.5)).into();
    /// assert!((command.0 - (-0.4_f64).to_degrees()).abs() < 1e-12);
    /// ```
    ///
    /// It lives here rather than in each consumer so that every consumer applies
    /// the same arithmetic. Publishing the contract is not commanding: nothing in
    /// this crate reaches hardware (ADR-0010).
    pub fn actuator_angle(&self, joint: Radians) -> Radians {
        let sign = if self.inverted { -1.0 } else { 1.0 };
        Radians(sign * joint.0 + self.zero_offset.map_or(0.0, |o| o.0))
    }
}

/// A cable, and the joints it crosses. **A cable that crosses a joint is a joint
/// limit** (ADR-0012): unless somebody left slack, it binds before the joint does.
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct CableRun {
    pub id: &'static str,
    pub crosses: &'static [&'static str],
    /// **`None` means NOBODY CHECKED** — never that it is fine. `Option<bool>` is
    /// load-bearing here: the compiler will not let a caller collapse the unknown
    /// case into the false case without writing it down.
    pub permits_full_travel: Option<bool>,
    /// Where the harness binds tighter than the joint. Only ever a limit somebody
    /// established, with a method.
    pub travel_limit: &'static [HarnessTravelLimit],
}

#[derive(Copy, Clone, PartialEq, Debug)]
pub struct HarnessTravelLimit {
    pub joint_id: &'static str,
    pub lower: Option<Radians>,
    pub upper: Option<Radians>,
    pub how_determined: &'static str,
}

#[derive(Copy, Clone, PartialEq, Debug)]
pub struct Power {
    /// Load-bearing: a torque figure is meaningless without its voltage, and a
    /// capacity derivation selects the actuator row matching THIS value
    /// (ADR-0014). `None` means no derivation is possible.
    pub supply_volts: Option<f64>,
    pub supply_current_a: Option<f64>,
    /// If true, an actuator stall can brown out the controller — turning a
    /// mechanical problem into a loss of control.
    pub shared_with_logic: Option<bool>,
}

/// What connects the actuators to the thing that drives them, and to power.
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct Harness {
    pub id: &'static str,
    pub robot_id: &'static str,
    pub controller_part_id: Option<&'static str>,
    pub channels: &'static [Channel],
    pub routing: &'static [CableRun],
    pub power: Power,
}

impl Harness {
    pub fn channel_for(&self, joint_id: &str) -> Option<&'static Channel> {
        self.channels.iter().find(|c| c.joint_id == joint_id)
    }

    /// Cable runs that cross a joint where nobody established what travel they
    /// permit. While this is non-empty, any reachability answer over this
    /// mechanism **over-claims**, and must say so (ADR-0012).
    pub fn unchecked_runs(&self) -> impl Iterator<Item = &'static CableRun> + '_ {
        self.routing.iter().filter(|r| {
            !r.crosses.is_empty()
                && r.permits_full_travel.is_none()
                && r.travel_limit.is_empty()
        })
    }
}

// NOTE: assemblies are not emitted. An assembly is a DAG of steps for a person at
// a bench — fasteners, torques, what cannot be undone — and no runtime consumes
// it. Adding it here would be data nothing reads, which ADR-0017's whole argument
// is against. It stays in `data/assemblies/` as JSON.

pub fn robot(id: &str) -> Option<&'static Robot> {
    ROBOTS.iter().find(|r| r.id == id)
}

pub fn actuator(id: &str) -> Option<&'static Actuator> {
    ACTUATORS.iter().find(|a| a.id == id)
}

/// The harness wiring a given robot, if one has been recorded. `None` means the
/// cable routing is unknown, which is not the same as "there are no cables".
pub fn harness_for(robot_id: &str) -> Option<&'static Harness> {
    HARNESSES.iter().find(|h| h.robot_id == robot_id)
}

'''


def render_vec3(value, default=0.0) -> str:
    value = value or {}
    return (f"Vec3 {{ x: {float(value.get('x', default))!r}_f64, "
            f"y: {float(value.get('y', default))!r}_f64, "
            f"z: {float(value.get('z', default))!r}_f64 }}")


def render_transform(origin) -> str:
    origin = origin or {}
    xyz = origin.get("xyz_mm") or {}
    rpy = origin.get("rpy_rad") or {}
    return (f"Transform {{ xyz_mm: {render_vec3(xyz)}, "
            f"rpy_rad: Vec3 {{ x: {float(rpy.get('r', 0.0))!r}_f64, "
            f"y: {float(rpy.get('p', 0.0))!r}_f64, "
            f"z: {float(rpy.get('y', 0.0))!r}_f64 }} }}")


def render_limits(limits) -> str:
    if not limits:
        return "None"
    def rad(key):
        v = limits.get(key)
        return "None" if v is None else f"Some(Radians({float(v)!r}_f64))"
    def mm(key):
        v = limits.get(key)
        return "None" if v is None else f"Some(Millimetres({float(v)!r}_f64))"
    return ("Some(JointLimits { "
            f"lower: {rad('lower_rad')}, upper: {rad('upper_rad')}, "
            f"lower_mm: {mm('lower_mm')}, upper_mm: {mm('upper_mm')}, "
            f"effort_nm: {rs_f64(limits.get('effort_nm'))}, "
            f"velocity_rad_s: {rs_f64(limits.get('velocity_rad_s'))} }})")


def render_joint(joint: dict) -> str:
    mimic = joint.get("mimic")
    mimic_rs = "None" if not mimic else (
        "Some(Mimic { joint: " + rs_str(mimic["joint"]) +
        f", multiplier: {float(mimic.get('multiplier', 1))!r}_f64"
        f", offset: {float(mimic.get('offset', 0))!r}_f64 }})")
    axis = joint.get("axis")
    axis_rs = "None" if not axis else f"Some({render_vec3(axis)})"
    kind = joint["type"].capitalize()
    return (
        "        Joint {\n"
        f"            id: {rs_str(joint['joint_id'])},\n"
        f"            kind: JointType::{kind},\n"
        f"            parent: {rs_str(joint['parent'])},\n"
        f"            child: {rs_str(joint['child'])},\n"
        f"            origin: {render_transform(joint.get('origin'))},\n"
        f"            axis: {axis_rs},\n"
        f"            limits: {render_limits(joint.get('limits'))},\n"
        f"            mimic: {mimic_rs},\n"
        f"            actuator_id: {rs(joint.get('actuator_id'))},\n"
        f"            gear_ratio: {rs_f64(joint.get('gear_ratio'))},\n"
        "        },\n"
    )


def render_link(link: dict) -> str:
    make = link.get("make")
    prov = link.get("provenance_ref") or {}
    size = "None" if not make else f"Some({render_vec3(make['size_mm'])})"
    return (
        "        Link {\n"
        f"            id: {rs_str(link['link_id'])},\n"
        f"            part_id: {rs(link.get('part_id'))},\n"
        f"            provenance_sha256: {rs(prov.get('artifact_sha256'))},\n"
        f"            make_size_mm: {size},\n"
        f"            make_material: {rs(make.get('material') if make else None)},\n"
        f"            mass_g: {rs_f64(link.get('mass_g'))},\n"
        "        },\n"
    )


def render_robot(robot: dict) -> str:
    links = "".join(render_link(l) for l in robot.get("links", []))
    joints = "".join(render_joint(j) for j in robot.get("joints", []))
    return (
        "    Robot {\n"
        f"        id: {rs_str(robot['robot_id'])},\n"
        f"        kind: {rs_str(robot.get('kind', 'arm'))},\n"
        f"        make: {rs(robot.get('make'))},\n"
        f"        model: {rs(robot.get('model'))},\n"
        f"        base_link: {rs_str(robot['base_link'])},\n"
        f"        links: &[\n{links}        ],\n"
        f"        joints: &[\n{joints}        ],\n"
        "    },\n"
    )


def range_rs(rng) -> str:
    if not rng:
        return "None"
    return ("Some(TorqueRange { "
            f"min: {float(rng['min'])!r}_f64, max: {float(rng['max'])!r}_f64, "
            f"how_determined: {rs_str(rng['how_determined'])}, "
            f"basis: {basis_rs(rng.get('basis'))} }})")


def basis_rs(value) -> str:
    if value is None:
        return "None"
    return {"model-typical": "Some(Basis::ModelTypical)",
            "this-unit": "Some(Basis::ThisUnit)"}[value]


def render_actuator(act: dict) -> str:
    stall = "".join(
        f"            StallTorque {{ newton_metres: {float(r['value'])!r}_f64, "
        f"at_volts: {float(r['at_volts'])!r}_f64, at_amps: {rs_f64(r.get('at_amps'))} }},\n"
        for r in act.get("stall_torque_nm") or [])
    cont = "".join(
        f"            ContinuousTorque {{ newton_metres: {float(r['value'])!r}_f64, "
        f"at_volts: {float(r['at_volts'])!r}_f64, "
        f"how_determined: {rs_str(r['how_determined'])} }},\n"
        for r in act.get("continuous_torque_nm") or [])
    holding = "".join(
        f"            HoldingTorque {{ newton_metres: {float(r['value'])!r}_f64, "
        f"at_amps: {float(r['at_amps'])!r}_f64 }},\n"
        for r in act.get("holding_torque_nm") or [])
    stall_f = "".join(
        f"            StallForce {{ newtons: {float(r['value'])!r}_f64, "
        f"at_volts: {float(r['at_volts'])!r}_f64, "
        f"at_amps: {rs_f64(r.get('at_amps'))} }},\n"
        for r in act.get("stall_force_n") or [])
    cont_f = "".join(
        f"            ContinuousForce {{ newtons: {float(r['value'])!r}_f64, "
        f"at_volts: {float(r['at_volts'])!r}_f64, "
        f"how_determined: {rs_str(r['how_determined'])} }},\n"
        for r in act.get("continuous_force_n") or [])
    gearbox = act.get("gearbox") or {}
    backlash = gearbox.get("backlash_rad")
    return (
        "    Actuator {\n"
        f"        id: {rs_str(act['actuator_id'])},\n"
        f"        make: {rs(act.get('make'))},\n"
        f"        model: {rs(act.get('model'))},\n"
        f"        kind: {rs_str(act['type'])},\n"
        f"        part_id: {rs(act.get('part_id'))},\n"
        f"        stall_torque: &[\n{stall}        ],\n"
        f"        holding_torque: &[\n{holding}        ],\n"
        f"        stall_force: &[\n{stall_f}        ],\n"
        f"        continuous_force: &[\n{cont_f}        ],\n"
        f"        duty_cycle_pct: {rs_f64(act.get('duty_cycle_pct'))},\n"
        f"        continuous_torque: &[\n{cont}        ],\n"
        f"        gear_ratio: {rs_f64(gearbox.get('ratio'))},\n"
        f"        backlash_rad: "
        + ("None" if backlash is None else f"Some(Radians({float(backlash)!r}_f64))")
        + ",\n"
        f"        mass_g: {rs_f64(act.get('mass_g'))},\n"
        f"        starting_torque_nm: {range_rs(gearbox.get('starting_torque_nm'))},\n"
        f"        backdriving_torque_nm: "
        f"{range_rs(gearbox.get('backdriving_torque_nm'))},\n"
        f"        basis: {basis_rs(gearbox.get('basis') or act.get('basis'))},\n"
        f"        spread_pct: "
        f"{rs_f64(gearbox.get('spread_pct') or act.get('spread_pct'))},\n"
        "    },\n"
    )


BUS_RS = {"pwm": "Pwm", "i2c": "I2c", "spi": "Spi", "uart": "Uart",
          "can": "Can", "rs485": "Rs485", "step-dir": "StepDir"}


def channel_id_rs(value) -> str:
    if value is None:
        return "None"
    if isinstance(value, bool):
        return "None"
    if isinstance(value, int):
        return f"Some(ChannelId::Number({value}))"
    return f"Some(ChannelId::Name({rs_str(str(value))}))"


def rad_rs(value) -> str:
    return "None" if value is None else f"Some(Radians({float(value)!r}_f64))"


def render_channel(ch: dict) -> str:
    bus = ch.get("bus")
    return (
        "        Channel {\n"
        f"            joint_id: {rs_str(ch.get('joint_id', ''))},\n"
        f"            channel: {channel_id_rs(ch.get('channel'))},\n"
        f"            bus: " + ("None" if bus is None else f"Some(Bus::{BUS_RS[bus]})")
        + ",\n"
        f"            bus_address: {channel_id_rs(ch.get('bus_address'))},\n"
        f"            inverted: {'true' if ch.get('inverted') else 'false'},\n"
        f"            zero_offset: {rad_rs(ch.get('zero_offset_rad'))},\n"
        "        },\n"
    )


def render_run(run: dict) -> str:
    crosses = ", ".join(rs_str(j) for j in run.get("crosses") or [])
    limits = "".join(
        "                HarnessTravelLimit { "
        f"joint_id: {rs_str(t.get('joint_id', ''))}, "
        f"lower: {rad_rs(t.get('lower_rad'))}, "
        f"upper: {rad_rs(t.get('upper_rad'))}, "
        f"how_determined: {rs_str(t.get('how_determined', ''))} }},\n"
        for t in run.get("travel_limit") or [])
    permits = run.get("permits_full_travel")
    return (
        "        CableRun {\n"
        f"            id: {rs_str(run.get('run_id', ''))},\n"
        f"            crosses: &[{crosses}],\n"
        f"            permits_full_travel: "
        + ("None" if permits is None else f"Some({'true' if permits else 'false'})")
        + ",\n"
        f"            travel_limit: &[\n{limits}            ],\n"
        "        },\n"
    )


def render_harness(h: dict) -> str:
    channels = "".join(render_channel(c) for c in h.get("channels") or [])
    routing = "".join(render_run(r) for r in h.get("routing") or [])
    power = h.get("power") or {}
    shared = power.get("shared_with_logic")
    controller = (h.get("controller") or {}).get("part_id")
    return (
        "    Harness {\n"
        f"        id: {rs_str(h['harness_id'])},\n"
        f"        robot_id: {rs_str(h.get('robot_id', ''))},\n"
        f"        controller_part_id: {rs(controller)},\n"
        f"        channels: &[\n{channels}        ],\n"
        f"        routing: &[\n{routing}        ],\n"
        "        power: Power {\n"
        f"            supply_volts: {rs_f64(power.get('supply_volts'))},\n"
        f"            supply_current_a: {rs_f64(power.get('supply_current_a'))},\n"
        f"            shared_with_logic: "
        + ("None" if shared is None else f"Some({'true' if shared else 'false'})")
        + ",\n"
        "        },\n"
        "    },\n"
    )


def render() -> str:
    robots = load("robots", "robot_id")
    actuators = load("actuators", "actuator_id")
    harnesses = load("harnesses", "harness_id")
    body = HEADER
    body += "/// Every robot record, sorted by id.\n"
    body += "pub const ROBOTS: &[Robot] = &[\n"
    body += "".join(render_robot(r) for r in robots)
    body += "];\n\n"
    body += "/// Every actuator record, sorted by id.\n"
    body += "pub const ACTUATORS: &[Actuator] = &[\n"
    body += "".join(render_actuator(a) for a in actuators)
    body += "];\n\n"
    body += "/// Every harness record, sorted by id. This is the control contract\n"
    body += "/// ADR-0010 promised: joint to physical output, plus the two facts no\n"
    body += "/// amount of modelling recovers — which way it was installed, and where\n"
    body += "/// its zero is.\n"
    body += "pub const HARNESSES: &[Harness] = &[\n"
    body += "".join(render_harness(h) for h in harnesses)
    body += "];\n"
    return body


def main() -> int:
    text = render()
    if "--check" in sys.argv[1:]:
        if not OUT.exists():
            print(f"binding missing: {OUT.relative_to(ROOT)} — run scripts/emit_rust.py",
                  file=sys.stderr)
            return 1
        if OUT.read_text(encoding="utf-8") != text:
            print(f"binding is stale: {OUT.relative_to(ROOT)} differs from the data. "
                  "Run scripts/emit_rust.py and commit the result.", file=sys.stderr)
            return 1
        print("binding up to date")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    counts = (len(load("robots", "robot_id")),
              len(load("actuators", "actuator_id")),
              len(load("harnesses", "harness_id")))
    print(f"wrote {OUT.relative_to(ROOT)} "
          f"({counts[0]} robot(s), {counts[1]} actuator(s), {counts[2]} harness(es))")
    return 0


if __name__ == "__main__":
    sys.exit(main())
